name: buscafarma
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: 0.19.0
  provider: ^6.1.5
  uuid: ^4.5.1
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0
  auto_size_text: ^3.0.0
  timeago: ^3.7.1
  from_css_color: ^2.0.0
  page_transition: ^2.2.1
  flutter_animate: ^4.5.2
  go_router: ^15.1.2
  mask_text_input_formatter: ^2.9.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  retrofit_generator: ^9.2.0
  json_serializable: ^6.9.5

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

